package com.company;

/**
 * Created by User on 11.12.2015.
 */
public enum Key {
    MENU,
    ADD_CLIENT,
    ADD_PRODUCT,
    ADD_CHARTER,
    ADD_PRODUCT_TO_CHARTER,
    PRINT_CLIENTS,
    PRINT_PRODUCTS,
    PRINT_CHARTERS_OF_CLIENT,
    PRINT_PRODUCTS_OF_CHARTER,
    PRINT_CHARTERS_OF_PRODUCT,
    DELETE_CLIENT,
    DELETE_PRODUCT,
    DELETE_CHARTER,
    DELTETE_PRODUCT_FROM_CHARTER,
    UPDATE_NAME,
    END;
}
